### PR TITLE
feat: add panic propagation opt to apmchiv5

### PR DESCRIPTION
**Pull request by ryanhallcs**
Adding an option to take advantage of panic propagation in go chi

### CODE REVIEW

**Comment by ryanhallcs** [comment]
I'm not sure of the automation but I signed the Contributor Agreement, please let me know if I should do something differently or if I just have to be patient :)

**Review by axw — APPROVED** [review]
Looks great, thanks @ryanhallcs!

**Comment by axw** [comment]
Thanks for your contribution!

**Pull request merged**
