### PR TITLE
ci: use latest go version

### PR DESCRIPTION
**Pull request by axw**
Go 1.14.2 was just released, fixing the panics we've
seen in module/apmrestful. Let's use the latest version
to keep with the times.

## Workaround from the Go installer in Windows.

As long as the go 1.14.2 is not published then we need to apply some workaround, for such, I included the workaround as part of the `scripts/jenkins/windows/install-tools.bat` script, in a nutshell, there is a new repo `https://github.com/v1v/chocolatey-packages` that hosts the installer definition.

### CODE REVIEW

**Comment by axw** [comment]
Some tests are broken when using modules. I'll come back to this.

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
Now we're waiting for go1.14.2 to be added to Chocolatey.

**Comment by axw** [comment]
@elastic/observablt-robots any chance I could get some help with updating Go to 1.14.2 for Windows CI? The latest "golang" package on Chocolatey is still 1.14.1: https://chocolatey.org/packages/golang#versionhistory. We may have to either provide some help there, or go another route.

**Comment by v1v** [comment]
> any chance I could get some help with updating Go to 1.14.2 for Windows CI? 

I'm trying with https://github.com/elastic/apm-agent-go/pull/759 to install golang for windows using [CreatePackagesQuickStart](https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart#quick-start-guide). For such I created https://github.com/v1v/chocolatey-packages that uses https://bitbucket.org/xoviat/chocolatey-packages/src/master/golang/1.14.1/ as the baseline and changed the 1.14.1 references to 1.14.2

I'll iterate a few times and I'll see what I get

**Comment by v1v** [comment]
I've just closed #759 after cherry picking its commits into this PR. So, I think we should be good to go

**Comment by axw** [comment]
Thanks @v1v - you rock!

**Comment by axw** [comment]
jenkins run the tests please

**Pull request merged**
