### PR TITLE
Sanitizing raw data (JSON)

### PR DESCRIPTION
**Pull request by jonathanschmittcs**
1. **sanitezer.go**: Improved the **sanitizeRequest** method adding **sanitizeRawData** method that sanitizes JSON body of http requests.
2. **sanitizer_test.go**: Created a unit test **TestSanitizeRaw**.

**Example:**
> **Matchers**: ["id", "cardNumber", "balance"]
> **Input**: {"id": "dce2be67-89e2-4232-9052-589f23b44224", "name": "jonathan", "accountInfo": {"cardNumber": "1234123412341234", "balance": 3520.50}}
> **Output**: {"id": "[REDACTED]", "name": "jonathan", "accountInfo": {"cardNumber": "[REDACTED]", "balance": "[REDACTED]"}}

### CODE REVIEW

**Comment by dmathieu** [comment]
I don't know about this. It could lead to unexpected performance issues
Also, this would be a new feature and this repository is in maintenance only.

**Comment by xcloudscript** [comment]
This is a real need, we adjust as necessary and contribute if you want. If it is not interesting or necessary, we can simply maintain a fork in our project here and meet our needs. Please report future updates.

**Comment by dmathieu** [comment]
Rather than maintain a fork, have you considered migrating to OpenTelemetry?
It doesn't have sensitive data redaction (though that's being worked on https://github.com/open-telemetry/oteps/pull/255), but it's way more modular than our agent, and censoring some data in a custom exporter would be rather easy.

**Comment by dmathieu** [comment]
Closing this, as the project does not accept new features, and this one could have performance issues.

**Pull request closed without merging**
