### PR TITLE
restore instrumentation nav

### PR DESCRIPTION
**Pull request by graphaelli**
https://www.elastic.co/guide/en/apm/agent/go/current/index.html currently renders as:

image

with `module/apmpgx` at the top level in the navigation.  This should restore the instrumentation navigation expected in the docs

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Thanks

**Comment by graphaelli** [comment]
preview looks good
image

**Comment by graphaelli** [comment]
@bmorelli25 is there a handy way to port this to `2.x` also?

**Comment by bmorelli25** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|2.x|[](https://github.com/elastic/apm-agent-go/pull/1372)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by graphaelli** [comment]
excellent, thanks!

**Comment by axw** [comment]
Oops. Thanks @graphaelli & @bmorelli25!

**Pull request merged**
