### PR TITLE
feat: add panic propagation option to gin middleware

### PR DESCRIPTION
**Pull request by miguelb**
If gin middleware catches a panic it bypasses other middleware panic handlers. This is an issue in our use case because we have middleware which sends panics to our notification/alert system. The changes in this PR is modeled from other modules which support `panicPropagation`.

### CODE REVIEW

**Comment by miguelb** [comment]
I did sign the contribution guidelines. Does this take some time before it gets picked up?

**Comment by axw** [comment]
@miguelb thanks for opening the PR!

It looks like your commit is not associated with the email you used to sign the CLA. I think what you need to do is configure `user.email` in git, recreate the commit, and force-push.

**Review by axw — APPROVED** [review]
Nice, thanks :)

**Comment by axw** [comment]
run elasticsearch-ci/docs

**Pull request merged**
