### PR TITLE
apmotel: add nil and recording checks to span.RecordError

### PR DESCRIPTION
**Pull request by jacksehr**
Addresses feature request https://github.com/elastic/apm-agent-go/issues/1565

From it:

> The apmotel bridge has proved extremely helpful in migrating to OpenTelemetry spans/tracers, but there is one noticeable difference inside the Span implementation: RecordError.
> 
> The OpenTelemetry SDK implementation of span.RecordError() [includes a nil check](https://github.com/open-telemetry/opentelemetry-go/blob/15f0ab964c4c21d3f2004db7f8642a1aa8597ffd/sdk/trace/span.go#L432-L435) for the error that is passed in.
> 
> In contrast, the apmotel implementation [does no such check](https://github.com/elastic/apm-agent-go/blob/main/module/apmotel/span.go#L131-L145). While this is understandable, and arguably more idiomatic, it introduces an issue where you cannot seamlessly drop in the bridge and use span.RecordError how you might expect to with the OpenTelemetry SDK.

This PR implements the mentioned nil/recording checking.

### CODE REVIEW

**Review by simitt — APPROVED** [review]
Thank you for the contribution @jacksehr! Changes look reasonable to me for otel alignment.

**Review by dmathieu — APPROVED** [review]

**Comment by dmathieu** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by shravanjeevan** [comment]
@dmathieu Would it be possible to get a minor version release with this change? We are waiting on it to progress some things. Thanks 🙏

**Comment by dmathieu** [comment]
I have released 2.4.8.

**Pull request merged**
