### PR TITLE
[apmfasthttp] Upgrade fasthttp to v1.28.0

### PR DESCRIPTION
**Pull request by savsgio**

### CODE REVIEW

**Comment by axw** [comment]
@savsgio what's the motivation behind this change? If users of apmfasthttp have a dependency on a newer version of fasthttp, then `go` will select that.

**Comment by savsgio** [comment]
Keep fasthttp updated here, only!

**Comment by axw** [comment]
I don't see why it's necessary. This module is only used by applications that already use fasthttp. Applications should be managing their own fasthttp dependency rather than relying on apmfasthttp to bump it.

**Comment by axw** [comment]
I don't want to set a precedent for repeatedly bumping dependency versions, so I'll close this. If you think there's a need for it, I'm happy to hear an argument and reconsider.

**Pull request closed without merging**
