### PR TITLE
Update chi version

### PR DESCRIPTION
**Pull request by ZzEeKkAa**
Update go module to the latest chi version.

### CODE REVIEW

**Comment by axw** [comment]
Thanks @ZzEeKkAa! Can you please [sign the CLA](https://www.elastic.co/contributor-agreement)?

**Comment by ZzEeKkAa** [comment]
@axw done.

**Review by axw — APPROVED** [review]

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
I will have to come back to this - it appears there's an issue with go-chi not building with older versions of Go. I suspect this is an existing issue, I'll look into it soon.

**Comment by axw** [comment]
@ZzEeKkAa can you please merge master? I've just fixed an issue causing CI to fail on your branch (https://github.com/elastic/apm-agent-go/pull/894)

**Comment by ZzEeKkAa** [comment]
@axw done.

**Comment by axw** [comment]
Thanks again!

**Pull request merged**
