### PR TITLE
tracer: Parse global labels per tracer

### PR DESCRIPTION
**Pull request by marclop**
## Description
This patch removes the `globalLabel` variable and one-time parsing of
the global labels, in favor of parsing the global labels individually
on tracer construction. This has the advantage that tracers that are
created after start-up will parse environment variables at that time
and not only when the `apm` package is imported.

Encountered while writing a systemtest for elastic/apm-server#8139.

### CODE REVIEW

**Review by axw — APPROVED** [review]
LGTM! Can you please add a changelog entry for this?

**Comment by kruskall** [comment]
Flaky test, I'll trigger another build

**Comment by marclop** [comment]
Thanks!

**Pull request merged**
