### PR TITLE
fixing wrong documents

### PR DESCRIPTION
**Pull request by insukcho**
- change gin gonic link
- add missing import in beego module snippet
- fix wrong controller name in beego module snippet

### CODE REVIEW

**Comment by insukcho** [comment]
Hey, team. I'm trying to follow your contribution guide [here](https://github.com/elastic/apm-agent-go/blob/master/CONTRIBUTING.md) for Doc modification, but I'm not sure I'm following the right process. Please correct me if I was wrong.

**Comment by olksdr** [comment]
@insukcho could you, please, squash the  1553283 together with following one? Since it's the one which was made with another settings and causing the problem now 😄

**Comment by axw** [comment]
@insukcho the changes themselves are good, thank you!

As @olksdr says, please squash the commits together - you can force push afterwards. The first commit was not made with your elastic email, which is causing the CLA check to fail.

**Comment by insukcho** [comment]
@axw @olksdr Thank you for your confirmation and helps. I dropped old commits and push with --force. It seems now working!

**Comment by axw** [comment]
Perfect, thanks @insukcho! :heart:

**Pull request merged**
