### PR TITLE
fix: panic on gocql

### PR DESCRIPTION
**Pull request by skynet2**
Currently there is a possibility to receive a panic, while using apmgocql module, this situation can occur while passing context which does not have apm transaction attached

### CODE REVIEW

**Comment by marclop** [comment]
@skynet2 thanks for submitting this contribution, the change looks sensible to me. Would you mind signing the contributor agreement? Here's a link to it: https://www.elastic.co/contributor-agreement.

**Comment by skynet2** [comment]
Hi @marclop ,
Done, thanks.

**Review by marclop — APPROVED** [review]
LGTM. Thank you for the contribution.

**Comment by marclop** [comment]
run elasticsearch-ci/docs

**Pull request merged**
