### PR TITLE
add span destination

### PR DESCRIPTION
**Pull request by ivybridge-3c33**
Add span destination for redisv8 hook to support elastic apm services map.

### CODE REVIEW

**Comment by axw** [comment]
@ivybridge-3c33 thanks for the PR!

A few initial comments:
 - Please [sign the CLA](https://www.elastic.co/contributor-agreement). We cannot accept any contributions without this.
 - We recently deprecated the service destination name; only Resource needs to be set.
 - Resource will be auto-inferred for "exit spans", introduced in https://github.com/elastic/apm-agent-go/pull/1003

Regarding that last point, I think the more natural way to get the destination set would be to change the `apm.StartSpan` calls to `apm.StartSpanOptions`, and pass in `apm.SpanOptions{ExitSpan: true}`. Then the calls to `span.Context.SetDestinationService` are not needed.

**Comment by ivybridge-3c33** [comment]
> @ivybridge-3c33 thanks for the PR!
> 
> A few initial comments:
> 
> * Please [sign the CLA](https://www.elastic.co/contributor-agreement). We cannot accept any contributions without this.
> * We recently deprecated the service destination name; only Resource needs to be set.
> * Resource will be auto-inferred for "exit spans", introduced in [Infer destination service resource adapt public api #1003](https://github.com/elastic/apm-agent-go/pull/1003)
> 
> Regarding that last point, I think the more natural way to get the destination set would be to change the `apm.StartSpan` calls to `apm.StartSpanOptions`, and pass in `apm.SpanOptions{ExitSpan: true}`. Then the calls to `span.Context.SetDestinationService` are not needed.

thank you Mr. 
It's ExitSpan is undefined on v1.13.1 
I've set destination service because of redis not show up on services map in kibana
how to fix this and next release, Does ExitSpan will support to this issue?

**Comment by axw** [comment]
@ivybridge-3c33 maybe you already saw, but v1.14.0 was just released which includes this change: https://github.com/elastic/apm-agent-go/releases/tag/v1.14.0

If you set `ExitSpan: true` then redis should show up on the service map. I think we should update the instrumentation module to do this by default. If you would like to open a new PR we would be happy to review that change - otherwise we can get to it later.

**Comment by ivybridge-3c33** [comment]
> @ivybridge-3c33 maybe you already saw, but v1.14.0 was just released which includes this change: https://github.com/elastic/apm-agent-go/releases/tag/v1.14.0
> 
> If you set `ExitSpan: true` then redis should show up on the service map. I think we should update the instrumentation module to do this by default. If you would like to open a new PR we would be happy to review that change - otherwise we can get to it later.

I'll try at latest version first,
Thank you for your support :)

**Comment by ivybridge-3c33** [comment]
@axw ExitSpan still not show up on the service map

**Comment by marclop** [comment]
@ivybridge-3c33 I tested starting the span with `ExitSpan: true` and it worked fine for me and was able to assert that the `span.Context.Destination.Service.Resource` is set to `"redis"` in the unit tests. My local changes are:

```diff
diff --git a/module/apmgoredisv8/hook.go b/module/apmgoredisv8/hook.go
index d524c7b..907c061 100644
--- a/module/apmgoredisv8/hook.go
+++ b/module/apmgoredisv8/hook.go
@@ -40,7 +40,9 @@ func NewHook() redis.Hook {
 
 // BeforeProcess initiates the span for the redis cmd
 func (r *hook) BeforeProcess(ctx context.Context, cmd redis.Cmder) (context.Context, error) {
-	_, ctx = apm.StartSpan(ctx, getCmdName(cmd), "db.redis")
+	_, ctx = apm.StartSpanOptions(ctx, getCmdName(cmd), "db.redis", apm.SpanOptions{
+		ExitSpan: true,
+	})
 	return ctx, nil
 }
 
@@ -63,7 +65,9 @@ func (r *hook) BeforeProcessPipeline(ctx context.Context, cmds []redis.Cmder) (c
 		cmdNameBuf.WriteString(getCmdName(cmd))
 	}
 
-	_, ctx = apm.StartSpan(ctx, cmdNameBuf.String(), "db.redis")
+	_, ctx = apm.StartSpanOptions(ctx, cmdNameBuf.String(), "db.redis", apm.SpanOptions{
+		ExitSpan: true,
+	})
 	return ctx, nil
 }
 
diff --git a/module/apmgoredisv8/hook_test.go b/module/apmgoredisv8/hook_test.go
index d76e0f3..60e836e 100644
--- a/module/apmgoredisv8/hook_test.go
+++ b/module/apmgoredisv8/hook_test.go
@@ -74,12 +74,15 @@ func TestHook(t *testing.T) {
 			assert.Equal(t, "PING", spans[0].Name)
 			assert.Equal(t, "db", spans[0].Type)
 			assert.Equal(t, "redis", spans[0].Subtype)
+			assert.Equal(t, "redis", spans[0].Context.Destination.Service.Resource)
 			assert.Equal(t, "GET", spans[1].Name)
 			assert.Equal(t, "db", spans[1].Type)
 			assert.Equal(t, "redis", spans[1].Subtype)
+			assert.Equal(t, "redis", spans[2].Context.Destination.Service.Resource)
 			assert.Equal(t, "(empty command)", spans[2].Name)
 			assert.Equal(t, "db", spans[2].Type)
 			assert.Equal(t, "redis", spans[2].Subtype)
+			assert.Equal(t, "redis", spans[2].Context.Destination.Service.Resource)
 		})
 	}
 }
@@ -102,6 +105,7 @@ func TestHookPipeline(t *testing.T) {
 			assert.Equal(t, "GET, SET, GET, (empty command)", spans[0].Name)
 			assert.Equal(t, "db", spans[0].Type)
 			assert.Equal(t, "redis", spans[0].Subtype)
+			assert.Equal(t, "redis", spans[0].Context.Destination.Service.Resource)
 		})
 	}
 }
@@ -132,6 +136,7 @@ func TestHookTxPipeline(t *testing.T) {
 			}
 			assert.Equal(t, "db", spans[0].Type)
 			assert.Equal(t, "redis", spans[0].Subtype)
+			assert.Equal(t, "redis", spans[0].Context.Destination.Service.Resource)
 		})
 	}
 }
```

Updating your PR to only use the `apm.SpanOptions{ExitSpan: true}` should do it without needing to manually set the destination service resource explicitly.

**Comment by ivybridge-3c33** [comment]
> @ivybridge-3c33 I tested starting the span with `ExitSpan: true` and it worked fine for me and was able to assert that the `span.Context.Destination.Service.Resource` is set to `"redis"` in the unit tests. My local changes are:
> 
> ```diff
> diff --git a/module/apmgoredisv8/hook.go b/module/apmgoredisv8/hook.go
> index d524c7b..907c061 100644
> --- a/module/apmgoredisv8/hook.go
> +++ b/module/apmgoredisv8/hook.go
> @@ -40,7 +40,9 @@ func NewHook() redis.Hook {
>  
>  // BeforeProcess initiates the span for the redis cmd
>  func (r *hook) BeforeProcess(ctx context.Context, cmd redis.Cmder) (context.Context, error) {
> -	_, ctx = apm.StartSpan(ctx, getCmdName(cmd), "db.redis")
> +	_, ctx = apm.StartSpanOptions(ctx, getCmdName(cmd), "db.redis", apm.SpanOptions{
> +		ExitSpan: true,
> +	})
>  	return ctx, nil
>  }
>  
> @@ -63,7 +65,9 @@ func (r *hook) BeforeProcessPipeline(ctx context.Context, cmds []redis.Cmder) (c
>  		cmdNameBuf.WriteString(getCmdName(cmd))
>  	}
>  
> -	_, ctx = apm.StartSpan(ctx, cmdNameBuf.String(), "db.redis")
> +	_, ctx = apm.StartSpanOptions(ctx, cmdNameBuf.String(), "db.redis", apm.SpanOptions{
> +		ExitSpan: true,
> +	})
>  	return ctx, nil
>  }
>  
> diff --git a/module/apmgoredisv8/hook_test.go b/module/apmgoredisv8/hook_test.go
> index d76e0f3..60e836e 100644
> --- a/module/apmgoredisv8/hook_test.go
> +++ b/module/apmgoredisv8/hook_test.go
> @@ -74,12 +74,15 @@ func TestHook(t *testing.T) {
>  			assert.Equal(t, "PING", spans[0].Name)
>  			assert.Equal(t, "db", spans[0].Type)
>  			assert.Equal(t, "redis", spans[0].Subtype)
> +			assert.Equal(t, "redis", spans[0].Context.Destination.Service.Resource)
>  			assert.Equal(t, "GET", spans[1].Name)
>  			assert.Equal(t, "db", spans[1].Type)
>  			assert.Equal(t, "redis", spans[1].Subtype)
> +			assert.Equal(t, "redis", spans[2].Context.Destination.Service.Resource)
>  			assert.Equal(t, "(empty command)", spans[2].Name)
>  			assert.Equal(t, "db", spans[2].Type)
>  			assert.Equal(t, "redis", spans[2].Subtype)
> +			assert.Equal(t, "redis", spans[2].Context.Destination.Service.Resource)
>  		})
>  	}
>  }
> @@ -102,6 +105,7 @@ func TestHookPipeline(t *testing.T) {
>  			assert.Equal(t, "GET, SET, GET, (empty command)", spans[0].Name)
>  			assert.Equal(t, "db", spans[0].Type)
>  			assert.Equal(t, "redis", spans[0].Subtype)
> +			assert.Equal(t, "redis", spans[0].Context.Destination.Service.Resource)
>  		})
>  	}
>  }
> @@ -132,6 +136,7 @@ func TestHookTxPipeline(t *testing.T) {
>  			}
>  			assert.Equal(t, "db", spans[0].Type)
>  			assert.Equal(t, "redis", spans[0].Subtype)
> +			assert.Equal(t, "redis", spans[0].Context.Destination.Service.Resource)
>  		})
>  	}
>  }
> ```
> 
> Updating your PR to only use the `apm.SpanOptions{ExitSpan: true}` should do it without needing to manually set the destination service resource explicitly.

thank you very much it's work, now my pr updated please review

**Review by axw — APPROVED** [review]
LGTM, thanks @ivybridge-3c33 !

**Pull request merged**
