### PR TITLE
ci: use the microbenchmarks-pool

### PR DESCRIPTION
**Pull request by v1v**
### What

From now on we will use the same CI workers for the benchmarking

### CODE REVIEW

**Comment by v1v** [comment]
run benchmark tests

**Comment by v1v** [comment]
run benchmark tests

**Review by cachedout — APPROVED** [review]

**Comment by v1v** [comment]
Benchmark stage ran successfully and other errors are related to the MacOS workers that were decommissioned and was not changed to use the Orka ones.

I'll merge this one now

**Comment by v1v** [comment]
Requires https://github.com/elastic/apm-agent-go/pull/1265 otherwise the MacOS stage will keep failing

**Comment by v1v** [comment]
run benchmark tests

**Pull request merged**
