### PR TITLE
feat: add 'service_target_*' fields to dropped spans metrics

### PR DESCRIPTION
**Pull request by kruskall**
Part of the implementation plan for span service target.

See https://github.com/elastic/apm/blob/main/specs/agents/tracing-spans-service-target.md

Closes https://github.com/elastic/apm-agent-go/issues/1291

### CODE REVIEW

**Review by axw — COMMENTED** [review]
Code looks good. Can you please add a test?

**Comment by simitt** [comment]
@kruskall @axw is this blocked by anything or is the only part missing to add a test?

**Comment by axw** [comment]
AFAICS this just needs a test.

**Comment by kruskall** [comment]
I've updated the test!

Should we remove destination service resource from dropped spans ?

**Review by axw — APPROVED** [review]
> Should we remove destination service resource from dropped spans ?

I think we should keep it for now, for compatibility with older servers.

**Pull request merged**
