### PR TITLE
Update redigo to v1.8.2 as v2.0.0 is too old

### PR DESCRIPTION
**Pull request by billyplus**
# What does this PR do?

According to [Issue](https://github.com/gomodule/redigo/issues/486):

> 2.0 is old, it was created as a new feature set but didn't make much progress. It's only been kept for compatibility for those that tried it.
>So in summary use 1.X (master) which is being actively supported.

# Why is it important?

v2.0.0 is outdated, last commit is on Mar 15, 2018.

### CODE REVIEW

**Comment by axw** [comment]
Thanks @billyplus! Fortunately there's no API breakage, so it looks like this will be straightforward. Can you please [sign the CLA](https://www.elastic.co/contributor-agreement)?

**Comment by billyplus** [comment]
ok, i had signed the CLA.

**Review by axw — APPROVED** [review]

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
Test failure is unrelated, I'll fix that later.

Thanks again @billyplus

**Pull request merged**
