### PR TITLE
Update GoFiber dependencies

### PR DESCRIPTION
**Pull request by gaby**
The current version used by `apm-agent-go` is quite a few versions behind the current GoFiber version.

### CODE REVIEW

**Comment by gaby** [comment]
CLA has been signed and submitted

**Review by axw — APPROVED** [review]

**Comment by axw** [comment]
@gaby we don't always update the library versions, as sometimes they introduce breaking changes in minor versions -- i.e. because they don't properly follow semantic versioning. If CI passes on all our supported Go versions, then it can be merged.

**Comment by gaby** [comment]
@axw I just realize that it wont pass for `go 1.15`. The fasthttp dependency requires 1.16. Any especific reason why elastic is testing against very old Go versions?

**Comment by axw** [comment]
@gaby the tests don't pass for 1.17 either:

```
# github.com/rivo/uniseg
Error: /home/runner/go/pkg/mod/github.com/rivo/uniseg@v0.4.3/properties.go:137:6: missing function body
Error: /home/runner/go/pkg/mod/github.com/rivo/uniseg@v0.4.3/properties.go:137:20: syntax error: unexpected [, expecting (
note: module requires Go 1.18
FAIL	go.elastic.co/apm/module/apmfiber/v2 [build failed]
```

> @axw I just realize that it wont pass for go 1.15. The fasthttp dependency requires 1.16. Any especific reason why elastic is testing against very old Go versions?

Because that's what we specified as the minimum Go version for v2. Changing the minimum version is a breaking change, so we will do that when we release v3.

I think we'll need to leave the package version in `go.mod` alone. Your application can specify a newer version and that will be used instead.

**Comment by gaby** [comment]
> @gaby the tests don't pass for 1.17 either:
> 
> ```
> # github.com/rivo/uniseg
> Error: /home/runner/go/pkg/mod/github.com/rivo/uniseg@v0.4.3/properties.go:137:6: missing function body
> Error: /home/runner/go/pkg/mod/github.com/rivo/uniseg@v0.4.3/properties.go:137:20: syntax error: unexpected [, expecting (
> note: module requires Go 1.18
> FAIL	go.elastic.co/apm/module/apmfiber/v2 [build failed]
> ```
> 
> > @axw I just realize that it wont pass for go 1.15. The fasthttp dependency requires 1.16. Any especific reason why elastic is testing against very old Go versions?
> 
> Because that's what we specified as the minimum Go version for v2. Changing the minimum version is a breaking change, so we will do that when we release v3.
> 
> I think we'll need to leave the module version in `go.mod` alone. Your application can specify a newer version and that will be used instead.

Sounds good. Thanks! You can close this if needed.

**Comment by axw** [comment]
@gaby will do - thanks for opening this anyway!

**Pull request closed without merging**
